languageCode = "en-us"
title = "Pupil Docs"
baseurl = "http://example.org/"
theme = "docuapi"

# config
config = "config.toml"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = true

ignoreFiles = ["README.*"]
